LOGGING_DIR = "./logs"
FREEZE_FILE_NAME = 'MNIST_model.pb'
OPTIMIZE_FILE_NAME = 'MNIST_optimized.pb'

BATCH_SIZE = 128
EPOCHS = 12

# input image dimensions
IMAGE_SIZE = 28
NUM_CLASSES = 10
INPUT_SHAPE = (IMAGE_SIZE, IMAGE_SIZE, 1)
